# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-20 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneroom', '0003_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='deposit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
